/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.fleetmanagement;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import database.CRUDOperations;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Lenovo
 */
public class AirlineLanding extends javax.swing.JFrame {

    /**
     * Creates new form Payroll_landing
     */
    MongoDatabase database;
    MongoCollection<Document> airplane;
    CRUDOperations crud = new CRUDOperations();
    
    public AirlineLanding(MongoDatabase database) {
        initComponents();
        this.database = database;
        populateTable("Boeing");
        airplane = crud.getCollection("airplanes", this.database);
        setLocationRelativeTo(null);
//        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
//        pack();
           setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightsTable = new javax.swing.JTable();
        searchFlightField = new javax.swing.JTextField();
        orgLabel = new javax.swing.JLabel();
        deleteAirlineBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boeingBtn = new javax.swing.JButton();
        airbusbtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        flightsTable.setRowHeight(50);
        flightsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flightsTable);

        searchFlightField.setText("Search Airplane by AirplaneNumber");
        searchFlightField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFlightFieldKeyPressed(evt);
            }
        });

        orgLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        orgLabel.setForeground(new java.awt.Color(255, 255, 255));
        orgLabel.setText("BOEING");

        deleteAirlineBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteAirlineBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        deleteAirlineBtn.setText("Delete Airline");
        deleteAirlineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAirlineBtnMouseClicked(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 51, 102));
        addBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add New Airline");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        boeingBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        boeingBtn.setText("BOEING");
        boeingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boeingBtnMouseClicked(evt);
            }
        });

        airbusbtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        airbusbtn.setText("AIRBUS");
        airbusbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airbusbtnMouseClicked(evt);
            }
        });
        airbusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airbusbtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airbusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boeingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(boeingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(airbusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(refreshBtn)
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/airplaneLanding.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(orgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(515, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteAirlineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAirlineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boeingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boeingBtnMouseClicked
        // TODO add your handling code here:
        populateTable("Boeing");
        orgLabel.setText("BOEING");
    }//GEN-LAST:event_boeingBtnMouseClicked

    private void airbusbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airbusbtnMouseClicked
        // TODO add your handling code here:
        populateTable("Airbus");
        orgLabel.setText("AIRBUS");
    }//GEN-LAST:event_airbusbtnMouseClicked

    private void searchFlightFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFlightFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
        
            String planeNumber = searchFlightField.getText();
            
            String[] columnNames = {"Flight", "Model", "Seats", "Engine", "aisle"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                   //all cells false
                   return false;
                };
            };
            
            Document doc =  crud.getFirstRecordByKey("flight", planeNumber, this.airplane) ;
            
            if(doc == null){
                JOptionPane.showMessageDialog(this,
                 "No Data Found!",
            "Plane Data",
            JOptionPane.ERROR_MESSAGE);
            }
            model.addRow(new Object[] { doc.get("flight").toString(), doc.get("model"), doc.get("seats"), doc.get("engine"), doc.get("aisle") });
            flightsTable.setModel(model);
        }
    }//GEN-LAST:event_searchFlightFieldKeyPressed

    private void flightsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsTableMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.getSelectedRow();
        
        
        String selectedFlight = (String) source.getValueAt(row, 0);
        ObjectId id = (ObjectId) crud.getFirstRecordByKey("flight", selectedFlight, this.airplane).get("_id");
        
        FleetManagement fm = new FleetManagement(database, id);
        fm.setDefaultCloseOperation(1);
        
    }//GEN-LAST:event_flightsTableMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        
        AddNewAirplane addNewAirline = new AddNewAirplane(this.database);
        addNewAirline.setDefaultCloseOperation(1);
    }//GEN-LAST:event_addBtnMouseClicked

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
        // TODO add your handling code here:
        populateTable(orgLabel.getText().equals("BOEING") ? "Boeing" : "Airbus");
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void deleteAirlineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAirlineBtnMouseClicked
        // TODO add your handling code here:
        
        JTable source = (JTable)evt.getSource();
        int row = source.getSelectedRow();
        
        
        String selectedFlight = (String) source.getValueAt(row, 0);
        ObjectId id = (ObjectId) crud.getFirstRecordByKey("flight", selectedFlight, this.airplane).get("_id");
        
        crud.deleteDocumentById("_id", id, airplane);
        
        crud.deleteDocumentById("planeId", id, crud.getCollection("trips", this.database));
        
        
        
    }//GEN-LAST:event_deleteAirlineBtnMouseClicked

    private void airbusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airbusbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airbusbtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    public void populateTable(String org){
    
        MongoCollection<Document> airplane = crud.getCollection("airplanes", this.database);
        
        FindIterable<Document> plane = airplane.find(new Document("company", org));
        
        
        MongoCursor<Document> cursor = plane.iterator();
        String[] columnNames = {"Flight", "Model", "Seats", "Engine", "aisle"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                   //all cells false
                   return false;
                };
        };
        try {
            while(cursor.hasNext()) {               
                Document doc = cursor.next();
                
                model.addRow(new Object[] { doc.get("flight").toString(), doc.get("model"), doc.get("seats"), doc.get("engine"), doc.get("aisle") });
            }
        } finally {
            cursor.close();
        }
        
        flightsTable.setModel(model);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton airbusbtn;
    private javax.swing.JButton boeingBtn;
    private javax.swing.JButton deleteAirlineBtn;
    private javax.swing.JTable flightsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgLabel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField searchFlightField;
    // End of variables declaration//GEN-END:variables
}
