/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.paint;

import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.bson.Document;
import org.bson.types.ObjectId;
import service.PaintHomeService;
import validation.Validation;

/**
 *
 * @author aayush
 */
public class PaintHome extends javax.swing.JFrame {

    /**
     * Creates new form PaintHome
     */
    String name;
    ObjectId userId;
    PaintHomeService service = new PaintHomeService();
    ArrayList<Document> recordsOfPaint;
    int row = -1;
    public PaintHome(String name, ObjectId objectId) throws ParseException {
        initComponents();
        setVisible(true);
//        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
//        pack();
         setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        this.name = name;
        this.userId = userId;
        System.out.println(this.name +" "+name);
        nameLabel.setText(name);
        fillTable();
    }
    
    private void fillTable() throws ParseException{
        
       // display data in table
        orderTable.setModel(
        service.getPaintRecords()
        );
        
        recordsOfPaint = service.getArrayData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBy = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JLabel();
        updateStatusBtn = new javax.swing.JLabel();
        newOrderBtn = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plane Number", "Date", "Status", "Color", "Due Date" }));

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Plane Number", "Engine", "Ordered By"
            }
        ));
        orderTable.setRowHeight(50);
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshBtn.setText("Refresh");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });

        updateStatusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateStatusBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateStatusBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateStatusBtn.setText("Update Status");
        updateStatusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateStatusBtnMouseClicked(evt);
            }
        });

        newOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        newOrderBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newOrderBtn.setText("Add Paint Job");
        newOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrderBtnMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateStatusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(newOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/paintJob.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
       private void refillTable(){
        
        JOptionPane.showMessageDialog(this, "No Records Found!");
        orderTable.setModel(
        service.returnTableModel(null)
        );
        recordsOfPaint = service.getArrayData();
    
    }
    private void newOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderBtnMouseClicked
        // TODO add your handling code here:
        AddPaintJob apj = new AddPaintJob(this.userId, service.getArrayData());
        apj.setDefaultCloseOperation(1);

    }//GEN-LAST:event_newOrderBtnMouseClicked

    private void updateStatusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateStatusBtnMouseClicked
        // TODO add your handling code here:

        if(row > -1){

            PaintStatus ps = new PaintStatus((ObjectId) recordsOfPaint.get(row).get("_id"));
            ps.setDefaultCloseOperation(1);
        }else{

            JOptionPane.showMessageDialog(this, "Please Select Row");
        }

    }//GEN-LAST:event_updateStatusBtnMouseClicked

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        // TODO add your handling code here:

        JTable source = (JTable)evt.getSource();
        row = source.rowAtPoint( evt.getPoint() );

    }//GEN-LAST:event_orderTableMouseClicked

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
        try {
            // TODO add your handling code here:
            
            service = new PaintHomeService();
            
            fillTable();
        } catch (ParseException ex) {
            Logger.getLogger(PaintHome.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        if(row > -1){

            service.deleteOrder(recordsOfPaint.get(row).get("_id"));
            JOptionPane.showMessageDialog(this, "Deleted");
            service = new PaintHomeService();
            try {
                fillTable();
            } catch (ParseException ex) {
                Logger.getLogger(PaintHome.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{

            JOptionPane.showMessageDialog(this, "Please Select Row");
        }
    }//GEN-LAST:event_deleteBtnMouseClicked
    
    // searches for fields based on user
    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
        String searchFor = searchField.getText();
        String searchByText = (String) searchBy.getSelectedItem();

        if(searchFor.length() > 0){
            switch(searchByText){

                case "Plane Number":
                    ArrayList<Document> recordsByPaint =  service.fetchByFilter("planeNumber", searchFor);

                    if(!recordsOfPaint.isEmpty()){

                        orderTable.setModel(
                            service.returnTableModel(recordsByPaint)
                        );

                    }else{

                        refillTable();
                    }

                    break;

                case "Date":

                    if(new Validation().dateValidate(searchFor)){

                        ArrayList<Document> recordsByDate = service.fetchByFilter("date", searchFor);

                        if(recordsByDate.size() > 0){
                            orderTable.setModel(
                                service.returnTableModel(recordsByDate)
                            );
                        }else{
                            refillTable();

                        }
                    }else{

                        refillTable();

                    }

                    break;

                case "Status":

                    ArrayList<Document> recordsByStatus = service.fetchByFilter("status", searchFor);

                    if(recordsByStatus.size() > 0){
                        orderTable.setModel(
                            service.returnTableModel(recordsByStatus)
                        );
                        recordsByPaint = service.getArrayData();
                    }else{

                        refillTable();
                    }
                    break;

                case "Color":

                    ArrayList<Document> recordsByColor = service.fetchByFilter("color", searchFor);

                    if(recordsByColor.size() > 0){

                        orderTable.setModel(
                            service.returnTableModel(recordsByColor)
                        );
                    }else{

                        refillTable();
                    }
                    break;

                case "Due Date":

                    if(new Validation().dateValidate(searchFor)){

                        ArrayList<Document> recordsByDate = service.fetchByFilter("dueDate", searchFor);

                        if(recordsByDate.size() > 0){
                            orderTable.setModel(
                                service.returnTableModel(recordsByDate)
                            );
                        }else{
                            refillTable();

                        }
                    }else{

                        refillTable();

                    }

                    break;

                default:
                refillTable();
                break;

            }

        }else{
           orderTable.setModel(
        service.returnTableModel(null)
            );
            recordsOfPaint = service.getArrayData();
        }
    }//GEN-LAST:event_searchBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel newOrderBtn;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel refreshBtn;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel updateStatusBtn;
    // End of variables declaration//GEN-END:variables
}
