/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import view.employee.EmployeeLogin;
import com.mongodb.client.MongoDatabase;
import view.maintainence.MaintainanceLanding;
import java.awt.Toolkit;

/**
 *
 * @author Asus
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    MongoDatabase database;
    public MainJFrame(MongoDatabase database) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.database = database;
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fleetMgmtBtn = new javax.swing.JButton();
        HRBtn = new javax.swing.JButton();
        FinanceBtn = new javax.swing.JButton();
        MtnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Final_Front.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        fleetMgmtBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        fleetMgmtBtn.setText("AIRLINE");
        fleetMgmtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fleetMgmtBtnMouseClicked(evt);
            }
        });
        fleetMgmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleetMgmtBtnActionPerformed(evt);
            }
        });

        HRBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        HRBtn.setText("EMPLOYEE");
        HRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRBtnActionPerformed(evt);
            }
        });

        FinanceBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        FinanceBtn.setText("FINANCE");
        FinanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanceBtnActionPerformed(evt);
            }
        });

        MtnBtn.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        MtnBtn.setText("MAINTAINANCE");
        MtnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(fleetMgmtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(HRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(FinanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(MtnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fleetMgmtBtn)
                    .addComponent(HRBtn)
                    .addComponent(FinanceBtn)
                    .addComponent(MtnBtn))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRBtnActionPerformed
        // TODO add your handling code here:
        EmployeeLogin empLogin = new EmployeeLogin(database);
        empLogin.setDefaultCloseOperation(1);

    }//GEN-LAST:event_HRBtnActionPerformed

    private void fleetMgmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleetMgmtBtnActionPerformed
        // TODO add your handling code here:
        Airline_Login AirLanding = new Airline_Login(database);
        AirLanding.setDefaultCloseOperation(1);
    }//GEN-LAST:event_fleetMgmtBtnActionPerformed

    private void MtnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtnBtnActionPerformed
        // TODO add your handling code here:
        MaintainanceLanding ml = new MaintainanceLanding();
        ml.setDefaultCloseOperation(1);
    }//GEN-LAST:event_MtnBtnActionPerformed

    private void FinanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanceBtnActionPerformed
        // TODO add your handling code here:
        financeLanding FinLanding = new financeLanding(database);
        FinLanding.setDefaultCloseOperation(1);
    }//GEN-LAST:event_FinanceBtnActionPerformed

    private void fleetMgmtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetMgmtBtnMouseClicked
        // TODO add your handling code here:
        Airline_Login al = new Airline_Login(database);
        al.setDefaultCloseOperation(1);
        
    }//GEN-LAST:event_fleetMgmtBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinanceBtn;
    private javax.swing.JButton HRBtn;
    private javax.swing.JButton MtnBtn;
    private javax.swing.JButton fleetMgmtBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
